config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create]

  resources :shopping_carts, only: [:index, :show, :new, :create] do
    resources :cart_members, only: [:create]
    resources :cart_items, only: [:show, :update, :destroy]
  end

  resources :items, only: [:index, :show, :new, :create] do
    resources :cart_items, only: [:create]
  end

  resources :cart_items, only: [:update]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
  # CATEGORIES = ["meats", "produce", "seafood", "drinks", "dairy", "grains", "canned", "frozen", "baking", "sauces", "cleaning", "hygiene", "other"]
  has_many :cart_items
  has_many :shopping_carts, through: :cart_items
  validates :name, presence: true, uniqueness: true
  # validates :category, inclusion: { in: CATEGORIES }
  enum category: [:meats, :produce, :seafood, :drinks, :dairy, :grains, :canned, :frozen, :baking, :spices, :sauces, :snacks, :cleaning, :hygiene, :other]
  has_many_attached :photos

  include PgSearch::Model

  pg_search_scope :search_by_keywords,
    against: [ :name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  has_many :cart_members
  has_many :users, through: :cart_members
  has_many :cart_items
  has_many :items, through: :cart_items
  validates :name, presence: true, uniqueness: true

  include PgSearch::Model

  pg_search_scope :search_by_keywords,
    against: [ :name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :set_shopping_cart, only: [:show]
  before_action :sanitize_page_params

  def index
    @shopping_carts = ShoppingCart.all
    if params[:query].present?
      @shopping_carts = @shopping_carts.search_by_keywords(params[:query])
    end
    if params[:filter].present?
      @shopping_carts = @shopping_carts.where(id: current_user.shopping_cart_ids)
    end
  end

  def show
    @users = User.all
    @cart_item = CartItem.new
    @cart_member = CartMember.new
    @cart_items = @shopping_cart.cart_items.where(bought: false)
    @bought_cart_items = @shopping_cart.cart_items.where('updated_at > ? AND bought = true',
    24.hours.ago).order(updated_at: :desc).limit(15)
    @frequently_bought_cart_items = @shopping_cart.cart_items.where(bought: true)
    .select(:item_id, 'COUNT(item_id)').group(:item_id).order(count: :desc).limit(10)
    @items = Item.all
    # @item = Item.find
    @shopping_carts = ShoppingCart.find(current_user.shopping_cart_ids)
  end

  def new
    @shopping_cart = ShoppingCart.new()
  end

  def create
    @shopping_cart = ShoppingCart.new(shopping_cart_params)
    if @shopping_cart.save
      @cart_member = CartMember.create(user: current_user, shopping_cart: @shopping_cart)
      redirect_to shopping_cart_path(@shopping_cart), notice: "Shopping cart was successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
  end

  private

  def set_shopping_cart
    @shopping_cart = ShoppingCart.find(params[:id])
  end

  def shopping_cart_params
    params.require(:shopping_cart).permit(:name)
  end

  def sanitize_page_params
    # params[:filter] = params[:filter].to_i
    # params[:id] = params[:id].to_i
  end

end

app/views/shopping_carts/_shopping_cart.html.erb
<div class="card mx-auto my-4
  <% if current_user.shopping_cart_ids.include?(shopping_cart.id) %>
  card-round my-carts
  <% else %>
  card-round-dashed
  <% end %>
  " style="width: 18rem;" data-purchased-checked-target="my-cart" data-purchase-checked-action="load@window->purchase-checked#connect">
  <div class="card-body">
    <h5 class="card-title pb-2"><%= shopping_cart.name %></h5>
    <h6 class="card-subtitle mb-4 text-muted"><%= shopping_cart.created_at.strftime("Created on %m/%d at %I:%M%p") %></h6>
    <p class="card-text mb-2 pb-4">This shopping cart has <%= pluralize shopping_cart.cart_members.count, "member" %></p>
    <% item_count = [] %>
    <% shopping_cart.cart_items.each do |cart_item| %>
      <% unless cart_item.bought? %>
        <% item_count << cart_item %>
      <% end %>
    <% end %>
    <p class="card-text mb-2 pb-4"><%= pluralize item_count.count, "item" %> in this cart</p>
    <% if current_user.shopping_cart_ids.include?(shopping_cart.id) %>
      <%= link_to "View cart", shopping_cart_path(shopping_cart), class: "btn btn-large btn-food" %>
    <% else %>
      <%= link_to "More info", shopping_cart_path(shopping_cart), class: "btn btn-large btn-food" %>
    <% end %>
  </div>
</div>

app/views/shopping_carts/index.html.erb
<h1 class="my-4">Here are the shopping carts</h1>
<%= form_with url: shopping_carts_path, method: :get, class: "d-flex my-2" do %>
  <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for a shopping cart"
    %>
  <%= submit_tag "Find", name: "", class: "btn" %>
<% end %>
<div class="row justify-content-between py-4" data-controller="purchase-checked">
  <% @shopping_carts.each do |shopping_cart| %>
    <%= render shopping_cart %>
  <% end %>
</div>

app/views/shopping_carts/new.html.erb
<h1>I want to create a new shopping cart</h1>
<%= simple_form_for @shopping_cart do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "btn" %>
  </div>
<% end %>

app/views/shopping_carts/show.html.erb
<div class="mt-4">
  <div>
    <h1><%= @shopping_cart.name %></h1>
    <%#= link_to "Back to my shopping carts", shopping_carts_path(filter: current_user.id) %>
  </div>
  <h5>Members in this cart</h2>
  <div class="d-flex align-items-start">
    <% @shopping_cart.cart_members.each do |member| %>
      <% user = member.user_id %>
      <p class="my-auto px-2">
        / <%= @users.find(user).username %>
      </p>
    <% end %>
  </div>
  <br>
  <div class="row d-flex">
    <% if current_user.shopping_cart_ids.include?(@shopping_cart.id) %>
    <div class="row nav-links mb-4">
      <%= link_to "Add a new item", new_item_path, class: "btn btn-nav" %>
      <%= link_to "Search for items", items_path, class: "btn btn-nav" %>
      <%= link_to "Back to my shopping carts", root_path, class: "btn btn-nav" %>
    </div>
  </div>
  <div class="row mx-1">
    <div class="col-lg-9 px-0 mb-4">
      <h5>Items in this cart</h5>
      <div class="row d-flex flex-wrap" data-controller="purchase-checked"
      data-purchase-checked-count-value="<%= @cart_items.count %>"
      data-purchase-checked-user-value="<%= current_user %>">
        <% @cart_items.each_with_index do |cart_item, index| %>
          <%= render cart_item %>
        <% end %>
        <button data-action="purchase-checked#purchase" class="btn-food">Purchase all checked items</button>
      </div>
    </div>
    <div class="row justify-content-around">
      <div class="col-lg-3 col-12 px-0 mb-4">
        <h5>Recently purchased</h5>
          <ul class="p-0">
            <% @bought_cart_items.each do |cart_item| %>
              <div class="card mb-3 bought">
                <div class="row g-0">
                  <div class="col-4">
                    <% cart_item.item.photos.each do |photo| %>
                      <%= cl_image_tag(photo.key, width: 120, height: 200, crop: :fit, class: "img-fluid rounded-start") %>
                    <% end %>
                  </div>
                  <div class="col-8">
                    <div class="card-body">
                      <h6 class="card-title"><%= cart_item.item.name %></h6>
                      <p class="card-text">Bought by: <%= cart_item.bought_by %></p>
                      <p class="card-text"><small class="text-body-secondary"><%= cart_item.updated_at.strftime("%m/%d at %I:%M%p") %></small></p>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </ul>
        </div>
        <div class="col-lg-3 col-12 px-0 mb-4">
          <h5>Frequently purchased</h5>
            <ul class="p-0">
              <% @frequently_bought_cart_items.each do |cart_item| %>
                <div class="card mb-3 bought">
                  <div class="row g-0">
                    <div class="col-4">
                      <% cart_item.item.photos.each do |photo| %>
                        <%= cl_image_tag(photo.key, width: 120, height: 200, crop: :fit, class: "img-fluid rounded-start") %>
                      <% end %>
                    </div>
                    <div class="col-8">
                      <div class="card-body">
                        <h6 class="card-title"><%= cart_item.item.name %></h6>
                        <h6 class="card-title"><%= cart_item.count %></h6>
                        <% @item = cart_item.item %>
                      </div>
                    </div>
                  </div>
                </div>
                <%= simple_form_for [@item, @cart_item] do |f| %>
                  <div class="form-inputs">
                    <%= f.input :shopping_cart_id, collection: @shopping_carts, as: :select %>
                  </div>
                  <div class="form-actions">
                    <%= f.button :submit, "Add to cart", class: "btn btn-food" %>
                  </div>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% else %>
      <%= simple_form_for [@shopping_cart, @cart_member] do |f| %>
        <div class="form-inputs">
        </div>
        <div class="form-actions">
          <%= f.button :submit, "Join this cart", class: "btn btn-nav" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>