config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create]

  resources :shopping_carts, only: [:index, :show, :new, :create] do
    resources :cart_members, only: [:create]
    resources :cart_items, only: [:show, :update, :destroy]
  end

  resources :items, only: [:index, :show, :new, :create] do
    resources :cart_items, only: [:create]
  end

  resources :cart_items, only: [:update]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
  # CATEGORIES = ["meats", "produce", "seafood", "drinks", "dairy", "grains", "canned", "frozen", "baking", "sauces", "cleaning", "hygiene", "other"]
  has_many :cart_items
  has_many :shopping_carts, through: :cart_items
  validates :name, presence: true, uniqueness: true
  # validates :category, inclusion: { in: CATEGORIES }
  enum category: [:meats, :produce, :seafood, :drinks, :dairy, :grains, :canned, :frozen, :baking, :spices, :sauces, :snacks, :cleaning, :hygiene, :other]
  has_many_attached :photos

  include PgSearch::Model

  pg_search_scope :search_by_keywords,
    against: [ :name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/views/pages/home.html.erb
<div class="home-page row d-flex justify-content-center">
  <% if user_signed_in? %>
    <h1 class="home-text">Welcome to GrocerEase <%= current_user.username %>!
    <% if current_user.shopping_cart_ids.size != 0 %>
      Here are your shopping carts</h1>
    <% else %>
      <%= link_to "Create a new shopping cart", new_shopping_cart_path, class: "btn" %>
    <% end %>
    <div class="row justify-content-between py-4">
      <% @shopping_carts.each do |shopping_cart| %>
        <%= render shopping_cart %>
      <% end %>
    </div>
    <%= Time.now - 86400 %>
  <% else %>
  <h1 class="home-text">Welcome to GrocerEase!</h1>
  <%= link_to "Login", new_user_session_path, class: "btn home-login" %>
  <% end %>
</div>


    <%# <div class="row cart-index-div my-4">
      <div class="card home-card text-center card-solid my-4" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">New</h5>
          <i class="fa-solid fa-cart-plus fa-4x"></i>
          <p class="card-text">Create a new shopping cart.</p>
        </div>
        <div class="align-items-center">
          <%= link_to "GO", new_shopping_cart_path, class: "btn btn-circle" %>
        <%# </div>
      </div>
      <div class="card home-card text-center card-solid my-4" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Join</h5>
          <i class="fa-solid fa-cart-arrow-down fa-4x py-2"></i>
          <p class="card-text">Become a member of an existing shopping cart.</p>
        </div>
        <div class="align-items-center">
          <%= link_to "GO", shopping_carts_path, class: "btn btn-circle" %>
        <%# </div>
      </div>
      <div class="card home-card text-center %>
      <%# if current_user.shopping_cart_ids.empty? %>
      <%# card-dashed %>
      <%# else %>
      <%# card-solid %>
      <%# end %>
      <%# my-4" style="width: 18rem;"> %>
        <%# <div class="card-body text-muted">
          <h5 class="card-title">View</h5>
          <i class="fa-solid fa-cart-shopping fa-4x py-2"></i>
          <p class="card-text">See all your shopping carts.</p>
        </div>
        <div class="align-items-center"> %>
        <%# if current_user.shopping_cart_ids.empty? %>
        <%#= link_to "GO", root_path, class: "btn btn-dashed" %>
        <%# else %>
        <%#= link_to "GO", shopping_carts_path(filter: current_user.id), class: "btn btn-circle" %>
        <%# end %>
        <%# </div>
      </div>
    </div> %>