config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create]

  resources :shopping_carts, only: [:index, :show, :new, :create] do
    resources :cart_members, only: [:create]
    resources :cart_items, only: [:show, :update, :destroy]
  end

  resources :items, only: [:index, :show, :new, :create] do
    resources :cart_items, only: [:create]
  end

  resources :cart_items, only: [:update]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :shopping_cart
  # enum bought: {remaining: "remaining", purchased: "purchased"}


  def bought?
    bought == true
  end

  # def valid
  #   if persisted?
  #     self.[:shopping_cart_id]
  #   else
  #     @cart_item.shopping_cart_id
  #   end
  # end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def show
    @cart_item = CartItem.find(params[:id])
    render json: @cart_item
  end

  def create
    @cart_item = CartItem.new()
    @item = Item.find(params[:item_id])
    @cart_item.item = @item
    @shopping_cart = ShoppingCart.find(params[:cart_item][:shopping_cart_id])
    @cart_item.shopping_cart = @shopping_cart
    @cart_item.added_by = current_user.username
    if @cart_item.save
      redirect_to shopping_cart_path(@shopping_cart), notice: "Item was successfully added!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    # @shopping_cart = ShoppingCart.find(params[:shopping_cart_id])
    @cart_item = CartItem.find(params[:id])
    @cart_item.bought?
    @cart_item.bought_by = current_user.username
    @cart_item.update(cart_item_params)
    respond_to do |format|
      format.text { render "shopping_carts/show", locals: {shopping_cart: @cart_item.shopping_cart},
      formats: [:html] }
      format.html { redirect_to shopping_cart_path(@cart_item.shopping_cart),
      notice: "Item was marked as purchased." }
    end
  end

  def destroy
    @shopping_cart = ShoppingCart.find(params[:id])
    @cart_item = CartItem.find(params[:shopping_cart_id])
    @cart_item.destroy
    # raise
    flash[:success] = "The item was removed."
    redirect_to shopping_cart_path(@shopping_cart)
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:item_id, :shopping_cart_id, :bought, :added_by, :bought_by)
  end
end

app/views/cart_items/_cart_item.html.erb
<div class="col-lg-4 col-6 cart-item-card">
  <div class="card">
    <% cart_item.item.photos.each do |photo| %>
      <%= cl_image_tag(photo.key, height: 400, width: 300, crop: :fit,
      class: "img-fluid") %>
    <% end %>
    <p class="mb-0 pb-4 text-truncate"><%= cart_item.item.name %></p>
    <p class="mb-0 pb-1">Added by: <%= cart_item.added_by %></p>
    <div class="row d-flex">
      <%= simple_form_for cart_item, html: { class: "buy-form",
      data: {purchase_checked_target: "form"}} do |f| %>
        <%= f.input :bought, as: :hidden, input_html: { value: true }, class: "mx-4" %>
        <%= f.input :bought_by, as: :hidden, input_html: { value: current_user.username } %>
        <%= f.submit 'Buy', class: 'btn btn-cart-item-buy' %>
      <% end %>
      <%= link_to "Remove", shopping_cart_cart_item_path(cart_item),
      data: { turbo_method: :delete }, class: "btn btn-cart-item-remove" %>
    </div>
  </div>
  <input class="mx-2" type="checkbox" data-purchase-checked-url-value="<%= cart_item_path(cart_item) %>"
  data-action="change->purchase-checked#check">
  <%#= cart_item_path(cart_item) %>
</div>