config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create]

  resources :shopping_carts, only: [:index, :show, :new, :create] do
    resources :cart_members, only: [:create]
    resources :cart_items, only: [:show, :update, :destroy]
  end

  resources :items, only: [:index, :show, :new, :create] do
    resources :cart_items, only: [:create]
  end

  resources :cart_items, only: [:update]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
  # CATEGORIES = ["meats", "produce", "seafood", "drinks", "dairy", "grains", "canned", "frozen", "baking", "sauces", "cleaning", "hygiene", "other"]
  has_many :cart_items
  has_many :shopping_carts, through: :cart_items
  validates :name, presence: true, uniqueness: true
  # validates :category, inclusion: { in: CATEGORIES }
  enum category: [:meats, :produce, :seafood, :drinks, :dairy, :grains, :canned, :frozen, :baking, :spices, :sauces, :snacks, :cleaning, :hygiene, :other]
  has_many_attached :photos

  include PgSearch::Model

  pg_search_scope :search_by_keywords,
    against: [ :name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :sanitize_page_params

  def index
    @items = Item.all
    # @shopping_cart = ShoppingCart.find(params[:shopping_cart_id])
    if params[:query].present?
      @items = Item.search_by_keywords(params[:query])
    end
    if params[:filter].present?
      @items = Item.where(category: params[:filter])
    end
    @items
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @shopping_carts = ShoppingCart.find(current_user.shopping_cart_ids)
  end

  def new
    @item = Item.new
    @shopping_carts = ShoppingCart.find(current_user.shopping_cart_ids)
    @cart_item = CartItem.new
  end

  def create
    @item = Item.new(item_params)
    @shopping_cart = ShoppingCart.find(params[:item][:shopping_carts])
    # raise
    @cart_item = CartItem.new
    if @item.save
      @cart_item = CartItem.create(item: @item, shopping_cart: @shopping_cart, added_by: current_user.username)
      redirect_to shopping_cart_path(@shopping_cart), notice: "New item was successfully added!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :category, photos: [])
  end

  def sanitize_page_params
    # params[:filter] = params[:filter].to_i
    # params[:id] = params[:id].to_i
  end

end

app/views/items/_item.html.erb
<div class="item-card">
  <% item.photos.each do |photo| %>
    <%= cl_image_tag(photo.key, height: 400, width: 300, crop: :fit, class: "img-fluid") %>
  <% end %>
  <p class="mb-0 text-truncate"><%= item.name %></p>
  <p class="mb-0"><%= link_to "See more", item_path(item), class: "btn btn-food" %></p>
</div>

app/views/items/index.html.erb
<div class="container my-4">
  <div class="row">
    <h1>These are the available items</h1>
    <%#= link_to "Back to shopping cart", shopping_cart_path(@shopping_cart) %>
  </div>
</div>
<%= render "shared/categories" %>
<%= form_with url: items_path, method: :get, class: "d-flex my-2" do %>
  <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for items here..."
    %>
  <%= submit_tag "Find", name: "", class: "btn" %>
<% end %>
<div class="item-index d-flex flex-wrap">
  <% @items.each do |item| %>
    <%= render item %>
  <% end %>
</div>

app/views/items/new.html.erb
<h1>I want to add a new item to this shopping cart</h1>
<%= simple_form_for [@item] do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :category, collection: Item.categories.keys %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :shopping_carts, collection: @shopping_carts, as: :select %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-food" %>
  </div>
<% end %>

app/views/items/show.html.erb
<%= @item.name %>
<% @item.photos.each do |photo| %>
  <%= cl_image_tag(photo.key, width: 400, height: 400, crop: :fit) %>
<% end %>
<%= simple_form_for [@item, @cart_item] do |f| %>
  <div class="form-inputs">
    <%= f.input :shopping_cart_id, collection: @shopping_carts, as: :select %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Add to cart", class: "btn btn-food" %>
  </div>
<% end %>

<%# It's Juniper's birthday! %>